services:
  _defaults:
    autoconfigure: true
    autowire: true

  StiSolutions\Apps\Imovit\Backend\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  StiSolutions\:
    resource: '../../../../src'
